USE ROLE USERADMIN;

//USER CREATION

CREATE OR REPLACE USER snowman
PASSWORD = 'sn0wf@ll'
LOGIN_NAME = 'snowstorm'
FIRST_NAME = 'Snow'
LAST_NAME = 'Storm'
EMAIL = 'snow.storm@snowflake.com'
MUST_CHANGE_PASSWORD = true
DEFAULT_WAREHOUSE = COMPUTE_WH;

USE ROLE SECURITYADMIN;

GRANT ROLE SYSADMIN TO USER snowman;

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SYSADMIN;


USE ROLE ACCOUNTADMIN;

SHOW USERS;

SHOW ROLES;
///////////////////////////////////////////////////////////////////////////////////////////

USE ROLE ACCOUNTADMIN;

SHOW USERS;

--CREATION
CREATE WAREHOUSE IF NOT EXISTS DBT_WH WITH WAREHOUSE_SIZE='X-SMALL';
CREATE DATABASE IF NOT EXISTS DBT_DB;
CREATE ROLE IF NOT EXISTS DBT_ROLE;

--SHOW GRANTS
SHOW GRANTS ON WAREHOUSE DBT_WH;

--GRANT WAREHOUSE ACCESS TO ROLE
GRANT USAGE ON WAREHOUSE DBT_WH TO ROLE DBT_ROLE;
--GRANT DATABASE ACCESS TO ROLE
GRANT ALL ON DATABASE DBT_DB TO ROLE DBT_ROLE;
--ASSIGN ROLE TO USER
GRANT ROLE DBT_ROLE TO USER KISHANMAY2025;


USE ROLE DBT_ROLE;
CREATE SCHEMA DBT_DB.DBT_SCHEMA;

USE ROLE ACCOUNTADMIN;
DROP WAREHOUSE IF EXISTS DBT_WH;
DROP DATABASE IF EXISTS DBT_DB;
DROP SCHEMA IF EXISTS DBT_SCHEMA;
