CREATE OR REPLACE TABLE AWS_S3_CUSTOMER_PROFILE(
    Customer_Ref_Number VARCHAR,
    Email VARCHAR,
    First_Name VARCHAR,
    Surname VARCHAR,
    Birth_Date DATE,
    Rewards_Program_ID VARCHAR

);

SHOW FILE FORMATS;--CUSTOMERFILECSV

CREATE FILE FORMAT AWS_S3_FILEFORMAT
TYPE=CSV,
SKIP_HEADER=1
DATE_FORMAT=AUTO;

CREATE OR REPLACE STAGE AWS_EXT_STAGE
FILE_FORMAT=AWS_S3_FILEFORMAT
URL='s3://mydcfiles/e-commerce/S3_Customer_Profile.csv';

SHOW STAGES;

LIST @AWS_EXT_STAGE;--ACCESS DENIED


COPY INTO AWS_S3_CUSTOMER_PROFILE
FROM @AWS_EXT_STAGE;--ACCESS DENIED

COPY INTO AWS_S3_CUSTOMER_PROFILE
FROM @AWS_EXT_STAGE
CREDENTIALS=(AWS_KEY_ID='AKIA6G7789562X6PRAQNNJ' AWS_SECRET_KEY='fbvoFZ8fZt020l125896kDza4WvMbziqtQVnQPiP0');

SELECT $1,$2 FROM @AWS_S3_EXT;--ACCESS DENIED

SELECT * FROM AWS_S3_CUSTOMER_PROFILE;

--STORAGE INTEGRATION

CREATE or replace STORAGE INTEGRATION AWS_S3_INT
    Type=External_stage
    Storage_provider=S3
    enabled=True   
    Storage_aws_role_arn='arn:aws:iam::9770xxxx7871:role/AWSS3DATAINGESTION'
    Storage_allowed_locations=('s3://mydcfiles/e-commerce/S3_Customer_Profile.csv');


DESC INTEGRATION AWS_S3_INT;

CREATE OR REPLACE STAGE AWS_S3_EXT
FILE_FORMAT=AWS_S3_FILEFORMAT
STORAGE_INTEGRATION=AWS_S3_INT
URL='s3://mydcfiles/e-commerce/S3_Customer_Profile.csv';

LIST @AWS_S3_EXT;

SELECT $1,$2,$3,$4 FROM @AWS_S3_EXT;

TRUNCATE TABLE AWS_S3_CUSTOMER_PROFILE;

COPY INTO AWS_S3_CUSTOMER_PROFILE
FROM @AWS_S3_EXT;

SELECT * FROM AWS_S3_CUSTOMER_PROFILE;

--SNOWPIPE

CREATE  PIPE AWS_S3_PIPE
AUTO_INGEST=TRUE
AS COPY INTO AWS_S3_CUSTOMER_PROFILE
FROM @AWS_S3_EXT;

SELECT * FROM AWS_S3_CUSTOMER_PROFILE;

SHOW PIPES;

DROP PIPE AWS_S3_PIPE;

SELECT SYSTEM$PIPE_STATUS('AWS_S3_PIPE');
--2025-06-04T11:56:38.442Z"


SELECT * FROM SNOWFLAKE.account_usage.copy_history WHERE PIPE_NAME='AWS_S3_PIPE';















