

--CREATE FILE FORMAT
CREATE OR REPLACE FILE FORMAT CustomerFileCSV
TYPE=CSV SKIP_HEADER=1
DATE_FORMAT='DD-MM-YYYY';

--CREATE INTERNAL STAGE
CREATE or REPLACE STAGE Customer_STAGE
FILE_FORMAT='CustomerFileCSV';


put file://Downloads\CustomerRecords.csv @CUSTOMER_STAGE;

CREATE or REPLACE TABLE CUSTOMER_TABLE(
Id varchar(30),
FirstName varchar(30),
LastName varchar(30),
Email varchar(30),
Phone varchar(30),
Company varchar(30),
Title varchar(30),
LastPurchaseDate DATE,
TotalSpent INT
);

ALTER TABLE CUSTOMER_TABLE
add ETLLodaTime DATETIME;


SELECT * from CUSTOMER_TABLE;

TRUNCATE TABLE CUSTOMER_TABLE;

SELECT $1,$2,$3,$4,$5,$6,$7 from @CUSTOMER_STAGE;

COPY INTO CUSTOMER_TABLE from @CUSTOMER_STAGE
VALIDATION_MODE=RETURN_ALL_ERRORS;

COPY INTO CUSTOMER_TABLE from @CUSTOMER_STAGE
PURGE=TRUE;


COPY INTO CUSTOMER_TABLE from @CUSTOMER_STAGE
ON_ERROR=CONTINUE;

COPY INTO CUSTOMER_TABLE from @CUSTOMER_STAGE
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
INCLUDE_METADATA = (FILENAME);

COPY INTO CUSTOMER_TABLE from @CUSTOMER_STAGE
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
INCLUDE_METADATA = (FILENAME=METADATA$FILENAME,ETLLodaTime=METADATA$START_SCAN_TIME);

SELECT CURRENT_VERSION();

















