SHOW STAGES;

LIST @STA_CSV;

COPY INTO @STA_CSV
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER;

COPY INTO @STA_CSV
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER
SINGLE=TRUE;

COPY INTO @STA_CSV/CustomerData.csv
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER
SINGLE=TRUE 
OVERWRITE=TRUE;

COPY INTO @STA_CSV/CustomerData.csv
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER
INCLUDE_QUERY_ID=TRUE;

COPY INTO @STA_CSV/CustomerDataWithDetailedOP.csv
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER
DETAILED_OUTPUT=TRUE;

COPY INTO @STA_CSV/CustomerDataWithDetailedOP.csv
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER
VALIDATION_MODE=RETURN_ROWS;

COPY INTO @STA_CSV/CustomerDataWitALLrows.csv
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER
VALIDATION_MODE=RETURN_ROWS
HEADER=TRUE;


--UNLOADING DATA SUPPORTS ONLY JSON/PARQUET/CSV.TSV FILE FORMATS

CREATE STAGE STAGEDATA;

LIST @STAGEDATA;

COPY FILES INTO @STAGEDATA
FROM @STA_CSV;

COPY FILES INTO @STAGEDATA
FROM @STA_CSV/CustomerDataWitALLrows.csv;

COPY FILES INTO @STAGEDATA
FROM @STA_CSV/CustomerDataWithDetailedOP.csv;

REMOVE @STAGEDATA;




