SHOW FILE_FORMATS;

CREATE TABLE "SIGMA"."PUBLIC"."SALES_JAN" ( Date TIMESTAMP_NTZ , "Store Name" VARCHAR , "Order Number" NUMBER(38, 0) , "Sku Number" VARCHAR , Quantity NUMBER(38, 0) , Cost NUMBER(38, 2) , Price NUMBER(38, 2) , Profit NUMBER(38, 16) , "Product Type" VARCHAR , "Product Family" VARCHAR , "Product Line" VARCHAR , Brand VARCHAR , "Product Name" VARCHAR ); 

CREATE TEMP FILE FORMAT "SIGMA"."PUBLIC"."temp_file_format_2025-05-24T09:04:08.988Z"
	TYPE=CSV
    SKIP_HEADER=1
    FIELD_DELIMITER=','
    TRIM_SPACE=TRUE
    FIELD_OPTIONALLY_ENCLOSED_BY='"'
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "SIGMA"."PUBLIC"."SALES_JAN" 
FROM (SELECT $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
	FROM '@"SIGMA"."PUBLIC"."__snowflake_temp_import_files__"') 
FILES = ('2025-05-24T09:03:13.809Z/Jan Sales.csv') 
FILE_FORMAT = '"SIGMA"."PUBLIC"."temp_file_format_2025-05-24T09:04:08.988Z"' 
ON_ERROR=ABORT_STATEMENT 
-- For more details, see: https://docs.snowflake.com/en/sql-reference/sql/copy-into-table

CREATE FILE FORMAT FEB_SALES
TYPE=CSV
SKIP_HEADER=1
FIELD_DELIMITER = ','
RECORD_DELIMITER='/n';

DESC FILE FORMAT FEB_SALES;


CREATE OR REPLACE TABLE JSONEXAMPLE_DATA(
    DataColumn VARIANT
);

CREATE OR REPLACE FILE FORMAT JSON_FILEFORMAT
TYPE=JSON;

SELECT * FROM JSONEXAMPLE_DATA;

TRUNCATE TABLE JSONEXAMPLE_DATA;
