--CREATE TARGET TABLE
CREATE OR REPLACE TABLE AWS_S3_CUSTOMER_PROFILE_2(
    Customer_Ref_Number VARCHAR,
    Email VARCHAR,
    First_Name VARCHAR,
    Surname VARCHAR,
    Birth_Date DATE,
    Rewards_Program_ID VARCHAR

);

SELECT * FROM AWS_S3_CUSTOMER_PROFILE_2;

SELECT SYSTEM$clustering_information('AWS_S3_CUSTOMER_PROFILE_2');

SHOW FILE FORMATS;

CREATE OR REPLACE FILE FORMAT AWS_S3_EXFILEFORMAT
TYPE=CSV,
SKIP_HEADER=1
DATE_FORMAT=AUTO;

--CREATE EXTERNAL STAGE
CREATE OR REPLACE STAGE AWS_S3_EXSTAGE
FILE_FORMAT=AWS_S3_EXFILEFORMAT
URL='s3://mydcfiles/customerprofile/';

LIST @AWS_S3_EXSTAGE;--ACCESS DENIED

--STORAGE INTEGRATION

CREATE or replace STORAGE INTEGRATION AWS_S3_EX_INT
    Type=External_stage
    Storage_provider=S3
    enabled=True   
    Storage_aws_role_arn='arn:aws:iam::977069957871:role/AWSS3DATAINGESTION'
    Storage_allowed_locations=('s3://mydcfiles/customerprofile/');


DESC INTEGRATION AWS_S3_EX_INT;

CREATE OR REPLACE STAGE AWS_S3_EXSTAGE
FILE_FORMAT=AWS_S3_EXFILEFORMAT
STORAGE_INTEGRATION=AWS_S3_EX_INT
URL='s3://mydcfiles/customerprofile/';

LIST @AWS_S3_EXSTAGE;

SELECT $1,$2,$3,$4 FROM @AWS_S3_EXSTAGE WHERE $3 IS NOT NULL;


--COPY INTO TABLE FROM EXTERNAL STAGE
COPY INTO AWS_S3_CUSTOMER_PROFILE_2
FROM @AWS_S3_EXSTAGE;

TRUNCATE TABLE AWS_S3_CUSTOMER_PROFILE_2;

SELECT * FROM AWS_S3_CUSTOMER_PROFILE_2 WHERE FIRST_NAME IS NOT NULL;

SELECT COUNT(*) FROM AWS_S3_CUSTOMER_PROFILE_2 WHERE FIRST_NAME IS NOT NULL;

--SNOWPIPE
DROP PIPE AWS_S3_EXPIPE;

CREATE  PIPE AWS_S3_EXPIPE
AUTO_INGEST=TRUE
AS COPY INTO AWS_S3_CUSTOMER_PROFILE_2
FROM @AWS_S3_EXSTAGE;

SHOW PIPES;

SELECT SYSTEM$PIPE_STATUS('AWS_S3_EXPIPE');
--"lastReceivedMessageTimestamp":"2025-06-05T03:39:33.455Z"
--"lastReceivedMessageTimestamp":"2025-06-05T03:41:43.464Z",
--"lastReceivedMessageTimestamp":"2025-06-05T03:48:43.441Z"

SELECT * FROM SNOWFLAKE.account_usage.copy_history WHERE PIPE_NAME='AWS_S3_EXPIPE';

--amazon sns services
--Currently, this feature is limited to Snowflake accounts hosted on AWS.

CREATE NOTIFICATION INTEGRATION my_snowpipe_notification_int
  ENABLED = TRUE
  DIRECTION = OUTBOUND
  TYPE = QUEUE
  NOTIFICATION_PROVIDER = AWS_SNS
  AWS_SNS_TOPIC_ARN = 'arn:aws:sns:ap-south-1:977069957871:SNOWPIPE_ALERT_NOTIFY'
  AWS_SNS_ROLE_ARN = 'arn:aws:iam::977069957871:role/AWSS3DATAINGESTION';

