INSERT INTO CUSTOMERS 
VALUES('2000','KISHAN','SURESH');

SELECT * FROM SIGMA.PUBLIC.CUSTOMERS;

SELECT * FROM ADDRESS;

SELECT Customer_ID FROM CUSTOMERS
INNER JOIN ADDRESS 
ON CUSTOMERS.Customer_ID = ADDRESS.CUSTOMER_ID;

SHOW DATABASES;

SELECT * FROM SALES_JAN;



