SHOW TABLES;

CREATE TRANSIENT TABLE TRANSIENT_TABLE(
    ID INT,
    NAME VARCHAR
);

CREATE TEMPORARY TABLE TEMPORORY_TABLE(
    ID INT,
    NAME VARCHAR
);

CREATE TEMPORARY TABLE EMPLOYEE(
    ID INT,
    NAME VARCHAR
);

CREATE GLOBAL TEMP TABLE GLOBAL_TEMP0RORY_TABLE(
    ID INT,
    NAME VARCHAR
);

DROP TABLE TRANSIENT_TABLE;
DROP TABLE TEMPORORY_TABLE;
DROP TABLE EMPLOYEE;
DROP TABLE GLOBAL_TEMP0RORY_TABLE;

-- CREATE HYBRID TABLE CUST_HYBRID(
--     EID INT PRIMARY KEY
-- );

CREATE OR REPLACE TABLE CLONE_TEMPORORY_TABLE
CLONE TEMPORORY_TABLE;

CREATE OR REPLACE TRANSIENT TABLE CLONE_TEMPORORY_TABLE
CLONE TEMPORORY_TABLE;
