SHOW TABLES;

SELECT * FROM MENU;

ALTER TABLE MENU
SET DATA_RETENTION_TIME_IN_DAYS=10;

show schemas;

DROP SCHEMA KISHANMAY2025_LOAD_SAMPLE_DATA_FROM_S3;

UNDROP SCHEMA KISHANMAY2025_LOAD_SAMPLE_DATA_FROM_S3;

ALTER SCHEMA KISHANMAY2025_LOAD_SAMPLE_DATA_FROM_S3
SET DATA_RETENTION_TIME_IN_DAYS=20;

SELECT * FROM MENU;

UPDATE MENU
SET MENU_ID= 100;

--3 WAYS TO ACCESS HISTORICAL DATA

--#1
SELECT * FROM MENU AT (OFFSET => -300);

--#2
SELECT * FROM MENU BEFORE (STATEMENT => '01bcf9b4-0001-02e0-0001-ffa6000e50ee');

--#3
SELECT * FROM MENU AT (TIMESTAMP => '2025-06-12 06:00:00');


SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.TABLE_STORAGE_METRICS;


